Fix for issue #359
BC-SECURITY/Empire pull request #361
Opened 2020-10-19 11:14 UTC by mjokic

Fix for issue #359  Invoke-PSRemoting blocks current agent.
I have added the 'AsJob' parameter which will run the new agent as a background job which won't block the current agent.

2020-10-20 03:17 UTC, Hubbl3 commented on lib/modules/powershell/lateral_movement/invoke_psremoting.py
> +        script = """Invoke-Command -AsJob"""
change back to original

2020-10-20 03:18 UTC, Hubbl3 requested changes

2020-10-20 03:18 UTC, Hubbl3 commented on lib/modules/powershell/lateral_movement/invoke_psremoting.py
> +        script = """Invoke-Command -AsJob"""
At line 24 change Background from False to true

2020-10-20 06:50 UTC, mjokic commented
I have applied the changes.

2020-10-20 08:23 UTC, mpgn commented
Happy to see my issue was valid ahaha

2020-10-21 23:47 UTC, Cx01N approved these changes

2020-10-22 04:45 UTC, Hubbl3 approved these changes

2020-10-22 04:47 UTC, merged